
export const products = [
    {
      productImage: "https://images.pexels.com/photos/6312048/pexels-photo-6312048.jpeg",
      tag: "Chair",
      title: "Comfy Chair",
      description: "Elegant and comfortable chair for your living room.",
      salePrice: 299,
      price: 499,
    },
    {
      productImage: "https://images.pexels.com/photos/4067759/pexels-photo-4067759.jpeg",
      tag: "Chair",
      title: "Modern Armchair",
      description: "Sleek design with high-quality materials.",
      salePrice: 349,
      price: 549,
    },
    {
      productImage: "https://images.pexels.com/photos/2495555/pexels-photo-2495555.jpeg",
      tag: "Chair",
      title: "Wooden Chair",
      description: "Classic wooden chair with smooth finish.",
      salePrice: 199,
      price: 399,
    },
    {
      productImage: "https://images.pexels.com/photos/2343468/pexels-photo-2343468.jpeg",
      tag: "Sofa",
      title: "Luxury Sofa",
      description: "Spacious sofa with velvet cushions.",
      salePrice: 899,
      price: 1299,
    },
    {
      productImage: "https://images.pexels.com/photos/11112731/pexels-photo-11112731.jpeg",
      tag: "Sofa",
      title: "2-Seater Sofa",
      description: "Compact and stylish for small spaces.",
      salePrice: 699,
      price: 999,
    },
    {
      productImage: "https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg",
      tag: "Sofa",
      title: "Sectional Sofa",
      description: "Perfect for large living rooms.",
      salePrice: 1099,
      price: 1499,
    },
    {
      productImage: "https://images.pexels.com/photos/3144581/pexels-photo-3144581.jpeg",
      tag: "Table",
      title: "Dining Table",
      description: "Solid wood dining table for 6.",
      salePrice: 499,
      price: 799,
    },
    {
      productImage: "https://images.pexels.com/photos/2988860/pexels-photo-2988860.jpeg",
      tag: "Table",
      title: "Coffee Table",
      description: "Minimalist center table for living room.",
      salePrice: 249,
      price: 399,
    },
    {
      productImage: "https://images.pexels.com/photos/3209035/pexels-photo-3209035.jpeg",
      tag: "Table",
      title: "Bedside Table",
      description: "Compact table for your bedroom essentials.",
      salePrice: 159,
      price: 259,
    },
    {
      productImage: "https://images.pexels.com/photos/939331/pexels-photo-939331.jpeg",
      tag: "Lamp",
      title: "Desk Lamp",
      description: "Bright and adjustable desk lamp.",
      salePrice: 89,
      price: 129,
    },
    {
      productImage: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg",
      tag: "Lamp",
      title: "Floor Lamp",
      description: "Elegant lamp for ambient lighting.",
      salePrice: 149,
      price: 199,
    },
    {
      productImage: "https://images.pexels.com/photos/3754594/pexels-photo-3754594.jpeg",
      tag: "Lamp",
      title: "Bedside Lamp",
      description: "Soft lighting for your nightstand.",
      salePrice: 99,
      price: 149,
    },
    {
      productImage: "https://images.pexels.com/photos/2898170/pexels-photo-2898170.jpeg",
      tag: "BookSelf",
      title: "Classic Bookshelf",
      description: "5-shelf unit with wooden finish.",
      salePrice: 299,
      price: 449,
    },
    {
      productImage: "https://images.pexels.com/photos/2228583/pexels-photo-2228583.jpeg",
      tag: "BookSelf",
      title: "Modern Bookshelf",
      description: "Geometric design with metal frame.",
      salePrice: 399,
      price: 599,
    },
    {
      productImage: "https://images.pexels.com/photos/7034294/pexels-photo-7034294.jpeg",
      tag: "BookSelf",
      title: "Corner Bookshelf",
      description: "Utilize space with this corner design.",
      salePrice: 199,
      price: 299,
    },
    {
      productImage: "https://images.pexels.com/photos/10388446/pexels-photo-10388446.jpeg",
      tag: "Chair",
      title: "Dining Chair",
      description: "Perfect match for your dining table.",
      salePrice: 129,
      price: 199,
    },
    {
      productImage: "https://images.pexels.com/photos/8581051/pexels-photo-8581051.jpeg",
      tag: "Chair",
      title: "Lounge Chair",
      description: "Relax in this low-seating chair.",
      salePrice: 349,
      price: 549,
    },
    {
      productImage: "https://images.pexels.com/photos/4930018/pexels-photo-4930018.jpeg",
      tag: "Chair",
      title: "Swivel Chair",
      description: "Ergonomic office swivel chair.",
      salePrice: 299,
      price: 449,
    },
    {
      productImage: "https://images.pexels.com/photos/8662029/pexels-photo-8662029.jpeg",
      tag: "Sofa",
      title: "Fabric Sofa",
      description: "Soft fabric upholstery for comfort.",
      salePrice: 799,
      price: 1099,
    },
    {
      productImage: "https://images.pexels.com/photos/5644367/pexels-photo-5644367.jpeg",
      tag: "Sofa",
      title: "Leather Sofa",
      description: "Premium leather 3-seater sofa.",
      salePrice: 1199,
      price: 1599,
    },
    {
      productImage: "https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg",
      tag: "Table",
      title: "Study Table",
      description: "Spacious and functional for students.",
      salePrice: 349,
      price: 499,
    },
    {
      productImage: "https://images.pexels.com/photos/24877169/pexels-photo-24877169.jpeg",
      tag: "Table",
      title: "Outdoor Table",
      description: "Weather-resistant patio table.",
      salePrice: 299,
      price: 459,
    },
    {
      productImage: "https://images.pexels.com/photos/284951/pexels-photo-284951.jpeg",
      tag: "Lamp",
      title: "Reading Lamp",
      description: "Focused lighting for reading corners.",
      salePrice: 119,
      price: 179,
    },
    {
      productImage: "https://images.pexels.com/photos/1129413/pexels-photo-1129413.jpeg",
      tag: "Lamp",
      title: "Hanging Lamp",
      description: "Modern pendant light for ceilings.",
      salePrice: 189,
      price: 249,
    },
    {
      productImage: "https://images.pexels.com/photos/6899536/pexels-photo-6899536.jpeg",
      tag: "BookSelf",
      title: "Glass Shelf",
      description: "Transparent shelves for a modern look.",
      salePrice: 249,
      price: 349,
    },
    {
      productImage: "https://images.pexels.com/photos/7578257/pexels-photo-7578257.jpeg",
      tag: "BookSelf",
      title: "Metal Bookshelf",
      description: "Durable steel frame with wood shelves.",
      salePrice: 329,
      price: 479,
    },
    {
      productImage: "https://images.pexels.com/photos/33985331/pexels-photo-33985331.jpeg",
      tag: "Chair",
      title: "Kids Chair",
      description: "Colorful chair designed for children.",
      salePrice: 99,
      price: 149,
    },
    {
      productImage: "https://images.pexels.com/photos/1957477/pexels-photo-1957477.jpeg",
      tag: "Chair",
      title: "Office Chair",
      description: "Comfortable ergonomic office seating.",
      salePrice: 399,
      price: 649,
    },
    {
      productImage: "https://images.pexels.com/photos/32984417/pexels-photo-32984417.jpeg",
      tag: "Sofa",
      title: "Convertible Sofa",
      description: "Sofa that transforms into a bed.",
      salePrice: 999,
      price: 1399,
    },
    {
      productImage: "https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg",
      tag: "Lamp",
      title: "Table Lamp",
      description: "Classic design with fabric shade.",
      salePrice: 79,
      price: 119,
    },
    {
      productImage: "https://images.pexels.com/photos/6312048/pexels-photo-6312048.jpeg",
      tag: "Chair",
      title: "Comfy Chair",
      description: "Elegant and comfortable chair for your living room.",
      salePrice: 299,
      price: 499,
    },
    {
      productImage: "https://images.pexels.com/photos/4067759/pexels-photo-4067759.jpeg",
      tag: "Chair",
      title: "Modern Armchair",
      description: "Sleek design with high-quality materials.",
      salePrice: 349,
      price: 549,
    },
    {
      productImage: "https://images.pexels.com/photos/2495555/pexels-photo-2495555.jpeg",
      tag: "Chair",
      title: "Wooden Chair",
      description: "Classic wooden chair with smooth finish.",
      salePrice: 199,
      price: 399,
    },
    {
      productImage: "https://images.pexels.com/photos/2343468/pexels-photo-2343468.jpeg",
      tag: "Sofa",
      title: "Luxury Sofa",
      description: "Spacious sofa with velvet cushions.",
      salePrice: 899,
      price: 1299,
    },
    {
      productImage: "https://images.pexels.com/photos/11112731/pexels-photo-11112731.jpeg",
      tag: "Sofa",
      title: "2-Seater Sofa",
      description: "Compact and stylish for small spaces.",
      salePrice: 699,
      price: 999,
    },
    {
      productImage: "https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg",
      tag: "Sofa",
      title: "Sectional Sofa",
      description: "Perfect for large living rooms.",
      salePrice: 1099,
      price: 1499,
    },
    {
      productImage: "https://images.pexels.com/photos/3144581/pexels-photo-3144581.jpeg",
      tag: "Table",
      title: "Dining Table",
      description: "Solid wood dining table for 6.",
      salePrice: 499,
      price: 799,
    },
    {
      productImage: "https://images.pexels.com/photos/2988860/pexels-photo-2988860.jpeg",
      tag: "Table",
      title: "Coffee Table",
      description: "Minimalist center table for living room.",
      salePrice: 249,
      price: 399,
    },
    {
      productImage: "https://images.pexels.com/photos/3209035/pexels-photo-3209035.jpeg",
      tag: "Table",
      title: "Bedside Table",
      description: "Compact table for your bedroom essentials.",
      salePrice: 159,
      price: 259,
    },
    {
      productImage: "https://images.pexels.com/photos/939331/pexels-photo-939331.jpeg",
      tag: "Lamp",
      title: "Desk Lamp",
      description: "Bright and adjustable desk lamp.",
      salePrice: 89,
      price: 129,
    },
    {
      productImage: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg",
      tag: "Lamp",
      title: "Floor Lamp",
      description: "Elegant lamp for ambient lighting.",
      salePrice: 149,
      price: 199,
    },
    {
      productImage: "https://images.pexels.com/photos/3754594/pexels-photo-3754594.jpeg",
      tag: "Lamp",
      title: "Bedside Lamp",
      description: "Soft lighting for your nightstand.",
      salePrice: 99,
      price: 149,
    },
    {
      productImage: "https://images.pexels.com/photos/2898170/pexels-photo-2898170.jpeg",
      tag: "BookSelf",
      title: "Classic Bookshelf",
      description: "5-shelf unit with wooden finish.",
      salePrice: 299,
      price: 449,
    },
    {
      productImage: "https://images.pexels.com/photos/2228583/pexels-photo-2228583.jpeg",
      tag: "BookSelf",
      title: "Modern Bookshelf",
      description: "Geometric design with metal frame.",
      salePrice: 399,
      price: 599,
    },
    {
      productImage: "https://images.pexels.com/photos/7034294/pexels-photo-7034294.jpeg",
      tag: "BookSelf",
      title: "Corner Bookshelf",
      description: "Utilize space with this corner design.",
      salePrice: 199,
      price: 299,
    },
    {
      productImage: "https://images.pexels.com/photos/10388446/pexels-photo-10388446.jpeg",
      tag: "Chair",
      title: "Dining Chair",
      description: "Perfect match for your dining table.",
      salePrice: 129,
      price: 199,
    },
    {
      productImage: "https://images.pexels.com/photos/8581051/pexels-photo-8581051.jpeg",
      tag: "Chair",
      title: "Lounge Chair",
      description: "Relax in this low-seating chair.",
      salePrice: 349,
      price: 549,
    },
    {
      productImage: "https://images.pexels.com/photos/4930018/pexels-photo-4930018.jpeg",
      tag: "Chair",
      title: "Swivel Chair",
      description: "Ergonomic office swivel chair.",
      salePrice: 299,
      price: 449,
    },
    {
      productImage: "https://images.pexels.com/photos/8662029/pexels-photo-8662029.jpeg",
      tag: "Sofa",
      title: "Fabric Sofa",
      description: "Soft fabric upholstery for comfort.",
      salePrice: 799,
      price: 1099,
    },
    {
      productImage: "https://images.pexels.com/photos/5644367/pexels-photo-5644367.jpeg",
      tag: "Sofa",
      title: "Leather Sofa",
      description: "Premium leather 3-seater sofa.",
      salePrice: 1199,
      price: 1599,
    },
    {
      productImage: "https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg",
      tag: "Table",
      title: "Study Table",
      description: "Spacious and functional for students.",
      salePrice: 349,
      price: 499,
    },
    {
      productImage: "https://images.pexels.com/photos/24877169/pexels-photo-24877169.jpeg",
      tag: "Table",
      title: "Outdoor Table",
      description: "Weather-resistant patio table.",
      salePrice: 299,
      price: 459,
    },
    {
      productImage: "https://images.pexels.com/photos/284951/pexels-photo-284951.jpeg",
      tag: "Lamp",
      title: "Reading Lamp",
      description: "Focused lighting for reading corners.",
      salePrice: 119,
      price: 179,
    },
    {
      productImage: "https://images.pexels.com/photos/1129413/pexels-photo-1129413.jpeg",
      tag: "Lamp",
      title: "Hanging Lamp",
      description: "Modern pendant light for ceilings.",
      salePrice: 189,
      price: 249,
    },
    {
      productImage: "https://images.pexels.com/photos/6899536/pexels-photo-6899536.jpeg",
      tag: "BookSelf",
      title: "Glass Shelf",
      description: "Transparent shelves for a modern look.",
      salePrice: 249,
      price: 349,
    },
    {
      productImage: "https://images.pexels.com/photos/7578257/pexels-photo-7578257.jpeg",
      tag: "BookSelf",
      title: "Metal Bookshelf",
      description: "Durable steel frame with wood shelves.",
      salePrice: 329,
      price: 479,
    },
    {
      productImage: "https://images.pexels.com/photos/33985331/pexels-photo-33985331.jpeg",
      tag: "Chair",
      title: "Kids Chair",
      description: "Colorful chair designed for children.",
      salePrice: 99,
      price: 149,
    },
    {
      productImage: "https://images.pexels.com/photos/1957477/pexels-photo-1957477.jpeg",
      tag: "Chair",
      title: "Office Chair",
      description: "Comfortable ergonomic office seating.",
      salePrice: 399,
      price: 649,
    },
    {
      productImage: "https://images.pexels.com/photos/32984417/pexels-photo-32984417.jpeg",
      tag: "Sofa",
      title: "Convertible Sofa",
      description: "Sofa that transforms into a bed.",
      salePrice: 999,
      price: 1399,
    },
    {
      productImage: "https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg",
      tag: "Lamp",
      title: "Table Lamp",
      description: "Classic design with fabric shade.",
      salePrice: 79,
      price: 119,
    },
    {
      productImage: "https://images.pexels.com/photos/6312048/pexels-photo-6312048.jpeg",
      tag: "Chair",
      title: "Comfy Chair",
      description: "Elegant and comfortable chair for your living room.",
      salePrice: 299,
      price: 499,
    },
    {
      productImage: "https://images.pexels.com/photos/4067759/pexels-photo-4067759.jpeg",
      tag: "Chair",
      title: "Modern Armchair",
      description: "Sleek design with high-quality materials.",
      salePrice: 349,
      price: 549,
    },
    {
      productImage: "https://images.pexels.com/photos/2495555/pexels-photo-2495555.jpeg",
      tag: "Chair",
      title: "Wooden Chair",
      description: "Classic wooden chair with smooth finish.",
      salePrice: 199,
      price: 399,
    },
    {
      productImage: "https://images.pexels.com/photos/2343468/pexels-photo-2343468.jpeg",
      tag: "Sofa",
      title: "Luxury Sofa",
      description: "Spacious sofa with velvet cushions.",
      salePrice: 899,
      price: 1299,
    },
    {
      productImage: "https://images.pexels.com/photos/11112731/pexels-photo-11112731.jpeg",
      tag: "Sofa",
      title: "2-Seater Sofa",
      description: "Compact and stylish for small spaces.",
      salePrice: 699,
      price: 999,
    },
    {
      productImage: "https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg",
      tag: "Sofa",
      title: "Sectional Sofa",
      description: "Perfect for large living rooms.",
      salePrice: 1099,
      price: 1499,
    },
    {
      productImage: "https://images.pexels.com/photos/3144581/pexels-photo-3144581.jpeg",
      tag: "Table",
      title: "Dining Table",
      description: "Solid wood dining table for 6.",
      salePrice: 499,
      price: 799,
    },
    {
      productImage: "https://images.pexels.com/photos/2988860/pexels-photo-2988860.jpeg",
      tag: "Table",
      title: "Coffee Table",
      description: "Minimalist center table for living room.",
      salePrice: 249,
      price: 399,
    },
    {
      productImage: "https://images.pexels.com/photos/3209035/pexels-photo-3209035.jpeg",
      tag: "Table",
      title: "Bedside Table",
      description: "Compact table for your bedroom essentials.",
      salePrice: 159,
      price: 259,
    },
    {
      productImage: "https://images.pexels.com/photos/939331/pexels-photo-939331.jpeg",
      tag: "Lamp",
      title: "Desk Lamp",
      description: "Bright and adjustable desk lamp.",
      salePrice: 89,
      price: 129,
    },
    {
      productImage: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg",
      tag: "Lamp",
      title: "Floor Lamp",
      description: "Elegant lamp for ambient lighting.",
      salePrice: 149,
      price: 199,
    },
    {
      productImage: "https://images.pexels.com/photos/3754594/pexels-photo-3754594.jpeg",
      tag: "Lamp",
      title: "Bedside Lamp",
      description: "Soft lighting for your nightstand.",
      salePrice: 99,
      price: 149,
    },
    {
      productImage: "https://images.pexels.com/photos/2898170/pexels-photo-2898170.jpeg",
      tag: "BookSelf",
      title: "Classic Bookshelf",
      description: "5-shelf unit with wooden finish.",
      salePrice: 299,
      price: 449,
    },
    {
      productImage: "https://images.pexels.com/photos/2228583/pexels-photo-2228583.jpeg",
      tag: "BookSelf",
      title: "Modern Bookshelf",
      description: "Geometric design with metal frame.",
      salePrice: 399,
      price: 599,
    },
    {
      productImage: "https://images.pexels.com/photos/7034294/pexels-photo-7034294.jpeg",
      tag: "BookSelf",
      title: "Corner Bookshelf",
      description: "Utilize space with this corner design.",
      salePrice: 199,
      price: 299,
    },
    {
      productImage: "https://images.pexels.com/photos/10388446/pexels-photo-10388446.jpeg",
      tag: "Chair",
      title: "Dining Chair",
      description: "Perfect match for your dining table.",
      salePrice: 129,
      price: 199,
    },
    {
      productImage: "https://images.pexels.com/photos/8581051/pexels-photo-8581051.jpeg",
      tag: "Chair",
      title: "Lounge Chair",
      description: "Relax in this low-seating chair.",
      salePrice: 349,
      price: 549,
    },
    {
      productImage: "https://images.pexels.com/photos/4930018/pexels-photo-4930018.jpeg",
      tag: "Chair",
      title: "Swivel Chair",
      description: "Ergonomic office swivel chair.",
      salePrice: 299,
      price: 449,
    },
    {
      productImage: "https://images.pexels.com/photos/8662029/pexels-photo-8662029.jpeg",
      tag: "Sofa",
      title: "Fabric Sofa",
      description: "Soft fabric upholstery for comfort.",
      salePrice: 799,
      price: 1099,
    },
    {
      productImage: "https://images.pexels.com/photos/5644367/pexels-photo-5644367.jpeg",
      tag: "Sofa",
      title: "Leather Sofa",
      description: "Premium leather 3-seater sofa.",
      salePrice: 1199,
      price: 1599,
    },
    {
      productImage: "https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg",
      tag: "Table",
      title: "Study Table",
      description: "Spacious and functional for students.",
      salePrice: 349,
      price: 499,
    },
    {
      productImage: "https://images.pexels.com/photos/24877169/pexels-photo-24877169.jpeg",
      tag: "Table",
      title: "Outdoor Table",
      description: "Weather-resistant patio table.",
      salePrice: 299,
      price: 459,
    },
    {
      productImage: "https://images.pexels.com/photos/284951/pexels-photo-284951.jpeg",
      tag: "Lamp",
      title: "Reading Lamp",
      description: "Focused lighting for reading corners.",
      salePrice: 119,
      price: 179,
    },
    {
      productImage: "https://images.pexels.com/photos/1129413/pexels-photo-1129413.jpeg",
      tag: "Lamp",
      title: "Hanging Lamp",
      description: "Modern pendant light for ceilings.",
      salePrice: 189,
      price: 249,
    },
    {
      productImage: "https://images.pexels.com/photos/6899536/pexels-photo-6899536.jpeg",
      tag: "BookSelf",
      title: "Glass Shelf",
      description: "Transparent shelves for a modern look.",
      salePrice: 249,
      price: 349,
    },
    {
      productImage: "https://images.pexels.com/photos/7578257/pexels-photo-7578257.jpeg",
      tag: "BookSelf",
      title: "Metal Bookshelf",
      description: "Durable steel frame with wood shelves.",
      salePrice: 329,
      price: 479,
    },
    {
      productImage: "https://images.pexels.com/photos/33985331/pexels-photo-33985331.jpeg",
      tag: "Chair",
      title: "Kids Chair",
      description: "Colorful chair designed for children.",
      salePrice: 99,
      price: 149,
    },
    {
      productImage: "https://images.pexels.com/photos/1957477/pexels-photo-1957477.jpeg",
      tag: "Chair",
      title: "Office Chair",
      description: "Comfortable ergonomic office seating.",
      salePrice: 399,
      price: 649,
    },
    {
      productImage: "https://images.pexels.com/photos/32984417/pexels-photo-32984417.jpeg",
      tag: "Sofa",
      title: "Convertible Sofa",
      description: "Sofa that transforms into a bed.",
      salePrice: 999,
      price: 1399,
    },
    {
      productImage: "https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg",
      tag: "Lamp",
      title: "Table Lamp",
      description: "Classic design with fabric shade.",
      salePrice: 79,
      price: 119,
    },
  ];
  