export const products = [
  // Mattress (12 items)
  {
    productImages: [
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Mattress",
    title: "Comfort Foam Mattress",
    description: "High density foam mattress for better sleep.",
    salePrice: 120,
    price: 180,
  },
  {
    productImages: [
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Mattress",
    title: "Spring Mattress",
    description: "Durable spring mattress with extra support.",
    salePrice: 150,
    price: 220,
  },
  {
    productImages: [
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Mattress",
    title: "Memory Foam Mattress",
    description: "Soft memory foam mattress that contours your body.",
    salePrice: 200,
    price: 270,
  },
  {
    productImages: [
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Mattress",
    title: "Gel Infused Mattress",
    description: "Cool gel-infused mattress for heat dissipation.",
    salePrice: 220,
    price: 300,
  },
  {
    productImages: [
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Mattress",
    title: "Latex Mattress",
    description: "Eco-friendly latex mattress with firm support.",
    salePrice: 250,
    price: 350,
  },
  {
    productImages: [
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Mattress",
    title: "Orthopedic Mattress",
    description: "Designed to support your spine and joints.",
    salePrice: 180,
    price: 260,
  },
  {
    productImages: [
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Mattress",
    title: "Pocket Spring Mattress",
    description: "Individual pocket springs for motion isolation.",
    salePrice: 210,
    price: 290,
  },
  {
    productImages: [
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Mattress",
    title: "Hybrid Mattress",
    description: "Combines foam and spring for balanced comfort.",
    salePrice: 230,
    price: 310,
  },
  {
    productImages: [
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Mattress",
    title: "Twin Mattress",
    description: "Compact mattress for single sleepers.",
    salePrice: 100,
    price: 140,
  },
  {
    productImages: [
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Mattress",
    title: "Queen Size Mattress",
    description: "Spacious mattress suitable for couples.",
    salePrice: 270,
    price: 370,
  },
  {
    productImages: [
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Mattress",
    title: "King Size Mattress",
    description: "Large mattress offering maximum comfort.",
    salePrice: 350,
    price: 470,
  },
  {
    productImages: [
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Mattress",
    title: "Foldable Mattress",
    description: "Convenient foldable mattress for guest use.",
    salePrice: 140,
    price: 190,
  },

  // Plastic Chair (12 items)
  {
    productImages: [
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Chair",
    title: "Stackable Plastic Chair",
    description: "Lightweight and easy to clean plastic chair.",
    salePrice: 25,
    price: 40,
  },
  {
    productImages: [
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Chair",
    title: "Outdoor Plastic Chair",
    description: "Weatherproof plastic chair for outdoor use.",
    salePrice: 30,
    price: 45,
  },
  {
    productImages: [
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Chair",
    title: "Plastic Armchair",
    description: "Comfortable plastic chair with armrests.",
    salePrice: 35,
    price: 50,
  },
  {
    productImages: [
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Chair",
    title: "Dining Plastic Chair",
    description: "Durable plastic chair for dining rooms.",
    salePrice: 28,
    price: 42,
  },
  {
    productImages: [
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Chair",
    title: "Folding Plastic Chair",
    description: "Portable folding chair made of plastic.",
    salePrice: 40,
    price: 55,
  },
  {
    productImages: [
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Chair",
    title: "Kids Plastic Chair",
    description: "Brightly colored chair designed for kids.",
    salePrice: 20,
    price: 30,
  },
  {
    productImages: [
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Chair",
    title: "Stacking Chair",
    description: "Space-saving stacking chair in multiple colors.",
    salePrice: 27,
    price: 38,
  },
  {
    productImages: [
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Chair",
    title: "High Back Plastic Chair",
    description: "Plastic chair with ergonomic high backrest.",
    salePrice: 33,
    price: 48,
  },
  {
    productImages: [
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Chair",
    title: "Plastic Lounge Chair",
    description: "Relaxing lounge chair made of durable plastic.",
    salePrice: 45,
    price: 60,
  },
  {
    productImages: [
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Chair",
    title: "Modern Plastic Chair",
    description: "Sleek plastic chair for modern interiors.",
    salePrice: 38,
    price: 52,
  },
  {
    productImages: [
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Chair",
    title: "Plastic Patio Chair",
    description: "Weather-resistant patio chair for outdoors.",
    salePrice: 30,
    price: 44,
  },
  {
    productImages: [
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/office-chair.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Chair",
    title: "Plastic Office Chair",
    description: "Basic plastic chair suitable for office use.",
    salePrice: 35,
    price: 50,
  },

  // Office Furniture (12 items)
  {
    productImages: [
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Office Furniture",
    title: "Ergonomic Office Chair",
    description: "Comfortable chair with adjustable height.",
    salePrice: 100,
    price: 150,
  },
  {
    productImages: [
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Office Furniture",
    title: "Office Desk with Drawer",
    description: "Spacious office desk with storage drawer.",
    salePrice: 200,
    price: 280,
  },
  {
    productImages: [
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Office Furniture",
    title: "L-Shaped Desk",
    description: "L-shaped desk to maximize office space.",
    salePrice: 320,
    price: 400,
  },
  {
    productImages: [
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Office Furniture",
    title: "Executive Office Chair",
    description: "Premium leather chair with lumbar support.",
    salePrice: 250,
    price: 350,
  },
  {
    productImages: [
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Office Furniture",
    title: "Filing Cabinet",
    description: "Metal filing cabinet with lockable drawers.",
    salePrice: 120,
    price: 160,
  },
  {
    productImages: [
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Office Furniture",
    title: "Conference Table",
    description: "Large table for meetings and conferences.",
    salePrice: 500,
    price: 650,
  },
  {
    productImages: [
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Office Furniture",
    title: "Office Bookshelf",
    description: "Wooden bookshelf for office storage.",
    salePrice: 180,
    price: 230,
  },
  {
    productImages: [
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Office Furniture",
    title: "Computer Desk",
    description: "Desk with keyboard tray and cable management.",
    salePrice: 210,
    price: 270,
  },
  {
    productImages: [
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Office Furniture",
    title: "Desk Chair Mat",
    description: "Protective mat for office chairs.",
    salePrice: 40,
    price: 55,
  },
  {
    productImages: [
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Office Furniture",
    title: "Adjustable Standing Desk",
    description: "Desk with adjustable height for standing work.",
    salePrice: 400,
    price: 550,
  },
  {
    productImages: [
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Office Furniture",
    title: "Reception Sofa",
    description: "Comfortable sofa for reception areas.",
    salePrice: 300,
    price: 420,
  },
  {
    productImages: [
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Office Furniture",
    title: "Workstation Partition",
    description: "Partitions to create private workstations.",
    salePrice: 150,
    price: 200,
  },

  // Wooden Furniture (12 items)
  {
    productImages: [
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Wooden Furniture",
    title: "Oak Wood Cabinet",
    description: "Elegant wooden cabinet with multiple shelves.",
    salePrice: 300,
    price: 400,
  },
  {
    productImages: [
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Wooden Furniture",
    title: "Pine Wood Side Table",
    description: "Rustic side table made from pine wood.",
    salePrice: 150,
    price: 210,
  },
  {
    productImages: [
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Wooden Furniture",
    title: "Mahogany Dining Chair",
    description: "Classic dining chair made of mahogany wood.",
    salePrice: 180,
    price: 230,
  },
  {
    productImages: [
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Wooden Furniture",
    title: "Teak Wood Coffee Table",
    description: "Durable coffee table crafted from teak wood.",
    salePrice: 220,
    price: 300,
  },
  {
    productImages: [
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Wooden Furniture",
    title: "Wooden Bookshelf",
    description: "Spacious bookshelf for living room or office.",
    salePrice: 250,
    price: 320,
  },
  {
    productImages: [
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Wooden Furniture",
    title: "Rustic Wooden Bench",
    description: "Sturdy wooden bench with rustic finish.",
    salePrice: 180,
    price: 240,
  },
  {
    productImages: [
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Wooden Furniture",
    title: "Wooden Shoe Rack",
    description: "Practical shoe rack made from solid wood.",
    salePrice: 120,
    price: 160,
  },
  {
    productImages: [
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Wooden Furniture",
    title: "Vintage Wooden Dresser",
    description: "Antique style wooden dresser with drawers.",
    salePrice: 350,
    price: 470,
  },
  {
    productImages: [
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Wooden Furniture",
    title: "Solid Wood Wardrobe",
    description: "Large wardrobe crafted from solid wood.",
    salePrice: 450,
    price: 600,
  },
  {
    productImages: [
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Wooden Furniture",
    title: "Wooden TV Stand",
    description: "Stylish TV stand with storage space.",
    salePrice: 270,
    price: 340,
  },
  {
    productImages: [
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Wooden Furniture",
    title: "Wooden Nightstand",
    description: "Compact nightstand with drawer.",
    salePrice: 110,
    price: 150,
  },
  {
    productImages: [
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/folding-bed.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Wooden Furniture",
    title: "Wooden Dining Bench",
    description: "Bench to complement dining tables.",
    salePrice: 190,
    price: 250,
  },
  // Folding Bed (12 items)
  {
    productImages: [
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Folding Bed",
    title: "Portable Folding Bed",
    description: "Easy to fold and carry bed for guests.",
    salePrice: 120,
    price: 170,
  },
  {
    productImages: [
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Folding Bed",
    title: "Metal Frame Folding Bed",
    description: "Sturdy metal folding bed with mattress.",
    salePrice: 130,
    price: 190,
  },
  {
    productImages: [
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Folding Bed",
    title: "Wooden Folding Bed",
    description: "Lightweight wooden folding bed for easy storage.",
    salePrice: 140,
    price: 200,
  },
  {
    productImages: [
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Folding Bed",
    title: "Deluxe Folding Bed",
    description: "Comfortable folding bed with thick mattress.",
    salePrice: 160,
    price: 220,
  },
  {
    productImages: [
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Folding Bed",
    title: "Camping Folding Bed",
    description: "Compact folding bed perfect for camping trips.",
    salePrice: 110,
    price: 160,
  },
  {
    productImages: [
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Folding Bed",
    title: "Adjustable Folding Bed",
    description: "Foldable bed with adjustable headrest.",
    salePrice: 170,
    price: 230,
  },
  {
    productImages: [
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Folding Bed",
    title: "Single Folding Bed",
    description: "Single bed folding for space saving.",
    salePrice: 100,
    price: 150,
  },
  {
    productImages: [
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Folding Bed",
    title: "Double Folding Bed",
    description: "Folding bed suitable for two adults.",
    salePrice: 200,
    price: 270,
  },
  {
    productImages: [
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Folding Bed",
    title: "Deluxe Camping Bed",
    description: "Sturdy bed with padded mattress for camping.",
    salePrice: 180,
    price: 240,
  },
  {
    productImages: [
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Folding Bed",
    title: "Kids Folding Bed",
    description: "Colorful folding bed designed for kids.",
    salePrice: 90,
    price: 130,
  },
  {
    productImages: [
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Folding Bed",
    title: "Lightweight Folding Bed",
    description: "Easy to carry lightweight folding bed.",
    salePrice: 110,
    price: 155,
  },
  {
    productImages: [
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/steel-almirah.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Folding Bed",
    title: "Compact Folding Bed",
    description: "Compact bed folds flat for easy storage.",
    salePrice: 130,
    price: 180,
  },

  // Steel Almirah (12 items)
  {
    productImages: [
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Steel Almirah",
    title: "2-Door Steel Almirah",
    description: "Durable steel almirah with lock system.",
    salePrice: 250,
    price: 350,
  },
  {
    productImages: [
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Steel Almirah",
    title: "3-Door Steel Almirah",
    description: "Spacious steel almirah with sleek finish.",
    salePrice: 400,
    price: 550,
  },
  {
    productImages: [
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Steel Almirah",
    title: "Steel Almirah with Glass Door",
    description: "Stylish almirah featuring glass panels.",
    salePrice: 450,
    price: 600,
  },
  {
    productImages: [
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Steel Almirah",
    title: "Single Door Steel Almirah",
    description: "Compact steel almirah for small spaces.",
    salePrice: 180,
    price: 250,
  },
  {
    productImages: [
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Steel Almirah",
    title: "Steel Almirah with Locker",
    description: "Almirah with multiple locker compartments.",
    salePrice: 320,
    price: 400,
  },
  {
    productImages: [
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Steel Almirah",
    title: "Steel Almirah with Mirror",
    description: "Almirah with built-in mirror on door.",
    salePrice: 380,
    price: 480,
  },
  {
    productImages: [
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Steel Almirah",
    title: "Lockable Steel Almirah",
    description: "Secure steel almirah with strong lock.",
    salePrice: 270,
    price: 350,
  },
  {
    productImages: [
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Steel Almirah",
    title: "Steel Almirah with Drawers",
    description: "Almirah with multiple drawers for storage.",
    salePrice: 360,
    price: 450,
  },
  {
    productImages: [
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Steel Almirah",
    title: "Rust-Resistant Steel Almirah",
    description: "Designed to resist rust and wear.",
    salePrice: 290,
    price: 380,
  },
  {
    productImages: [
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Steel Almirah",
    title: "Steel Almirah with Shelves",
    description: "Almirah featuring adjustable shelves.",
    salePrice: 340,
    price: 420,
  },
  {
    productImages: [
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Steel Almirah",
    title: "Compact Steel Almirah",
    description: "Space-saving steel almirah for apartments.",
    salePrice: 220,
    price: 300,
  },
  {
    productImages: [
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/plastic-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Steel Almirah",
    title: "Heavy Duty Steel Almirah",
    description: "Extra strong almirah for heavy storage.",
    salePrice: 400,
    price: 520,
  },

  // Plastic Table (12 items)
  {
    productImages: [
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Table",
    title: "Round Plastic Table",
    description: "Durable plastic table for indoor/outdoor use.",
    salePrice: 40,
    price: 60,
  },
  {
    productImages: [
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Table",
    title: "Square Plastic Table",
    description: "Compact plastic table for small spaces.",
    salePrice: 35,
    price: 50,
  },
  {
    productImages: [
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Table",
    title: "Folding Plastic Table",
    description: "Portable folding table with sturdy legs.",
    salePrice: 45,
    price: 65,
  },
  {
    productImages: [
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Table",
    title: "Kids Plastic Table",
    description: "Brightly colored plastic table for children.",
    salePrice: 30,
    price: 45,
  },
  {
    productImages: [
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Table",
    title: "Outdoor Plastic Table",
    description: "Weather-resistant plastic table for patio.",
    salePrice: 50,
    price: 70,
  },
  {
    productImages: [
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Table",
    title: "High Top Plastic Table",
    description: "Tall plastic table for casual dining.",
    salePrice: 55,
    price: 75,
  },
  {
    productImages: [
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Table",
    title: "Plastic Coffee Table",
    description: "Stylish coffee table made from plastic.",
    salePrice: 45,
    price: 60,
  },
  {
    productImages: [
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Table",
    title: "Foldable Picnic Table",
    description: "Perfect table for picnics and outdoor events.",
    salePrice: 60,
    price: 80,
  },
  {
    productImages: [
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Table",
    title: "Stacking Plastic Table",
    description: "Easy to stack and store plastic tables.",
    salePrice: 35,
    price: 50,
  },
  {
    productImages: [
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Table",
    title: "Kids Activity Table",
    description: "Table designed for kids’ arts and crafts.",
    salePrice: 40,
    price: 55,
  },
  {
    productImages: [
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Table",
    title: "Multi-Purpose Plastic Table",
    description: "Table suitable for many indoor/outdoor uses.",
    salePrice: 45,
    price: 60,
  },
  {
    productImages: [
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/sofa.webp",
      "/src/assets/dining-table.webp",
    ],
    tag: "Plastic Table",
    title: "Outdoor Folding Table",
    description: "Foldable and easy to carry outdoor table.",
    salePrice: 50,
    price: 65,
  },

  // Sofa (12 items)
  {
    productImages: [
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/dining-table.webp",
    ],
    tag: "Sofa",
    title: "3-Seater Fabric Sofa",
    description: "Comfortable 3-seater sofa with soft fabric.",
    salePrice: 350,
    price: 480,
  },
  {
    productImages: [
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/dining-table.webp",
    ],
    tag: "Sofa",
    title: "Leather Recliner Sofa",
    description: "Premium leather sofa with recliner feature.",
    salePrice: 600,
    price: 800,
  },
  {
    productImages: [
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/dining-table.webp",
    ],
    tag: "Sofa",
    title: "Sectional Sofa",
    description: "L-shaped sectional sofa for large living rooms.",
    salePrice: 750,
    price: 950,
  },
  {
    productImages: [
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/dining-table.webp",
    ],
    tag: "Sofa",
    title: "Loveseat Sofa",
    description: "Compact loveseat for small spaces.",
    salePrice: 280,
    price: 360,
  },
  {
    productImages: [
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/dining-table.webp",
    ],
    tag: "Sofa",
    title: "Futon Sofa Bed",
    description: "Convertible futon sofa that doubles as a bed.",
    salePrice: 400,
    price: 550,
  },
  {
    productImages: [
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/dining-table.webp",
    ],
    tag: "Sofa",
    title: "Modern Sofa",
    description: "Stylish sofa with minimalist design.",
    salePrice: 450,
    price: 600,
  },
  {
    productImages: [
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/dining-table.webp",
    ],
    tag: "Sofa",
    title: "Velvet Sofa",
    description: "Soft velvet sofa with elegant look.",
    salePrice: 500,
    price: 650,
  },
  {
    productImages: [
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/dining-table.webp",
    ],
    tag: "Sofa",
    title: "Outdoor Sofa",
    description: "Weather-resistant sofa for outdoor use.",
    salePrice: 550,
    price: 700,
  },
  {
    productImages: [
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/dining-table.webp",
    ],
    tag: "Sofa",
    title: "Chaise Lounge Sofa",
    description: "Comfortable chaise lounge with padded cushions.",
    salePrice: 480,
    price: 620,
  },
  {
    productImages: [
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/dining-table.webp",
    ],
    tag: "Sofa",
    title: "Fabric Sofa Set",
    description: "Complete sofa set with three pieces.",
    salePrice: 800,
    price: 1000,
  },
  {
    productImages: [
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/dining-table.webp",
    ],
    tag: "Sofa",
    title: "Classic Leather Sofa",
    description: "Timeless leather sofa with solid wood frame.",
    salePrice: 700,
    price: 900,
  },
  {
    productImages: [
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
      "/src/assets/dining-table.webp",
    ],
    tag: "Sofa",
    title: "Convertible Sofa",
    description: "Sofa that converts into a bed for guests.",
    salePrice: 430,
    price: 580,
  },

  // Dining Table (12 items)
  {
    productImages: [
      "/src/assets/dining-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
    ],
    tag: "Dining Table",
    title: "Wooden Dining Table",
    description: "Classic wooden dining table seating 6 people.",
    salePrice: 500,
    price: 650,
  },
  {
    productImages: [
      "/src/assets/dining-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
    ],
    tag: "Dining Table",
    title: "Glass Top Dining Table",
    description: "Modern glass top dining table with steel legs.",
    salePrice: 450,
    price: 600,
  },
  {
    productImages: [
      "/src/assets/dining-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
    ],
    tag: "Dining Table",
    title: "Extendable Dining Table",
    description: "Extendable table to seat up to 8 people.",
    salePrice: 600,
    price: 800,
  },
  {
    productImages: [
      "/src/assets/dining-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
    ],
    tag: "Dining Table",
    title: "Round Dining Table",
    description: "Round table ideal for small family meals.",
    salePrice: 400,
    price: 520,
  },
  {
    productImages: [
      "/src/assets/dining-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
    ],
    tag: "Dining Table",
    title: "Outdoor Dining Table",
    description: "Weatherproof dining table for outdoor use.",
    salePrice: 550,
    price: 700,
  },
  {
    productImages: [
      "/src/assets/dining-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
    ],
    tag: "Dining Table",
    title: "Rustic Dining Table",
    description: "Dining table with rustic wooden finish.",
    salePrice: 480,
    price: 620,
  },
  {
    productImages: [
      "/src/assets/dining-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
    ],
    tag: "Dining Table",
    title: "Industrial Dining Table",
    description: "Dining table with metal frame and wood top.",
    salePrice: 530,
    price: 680,
  },
  {
    productImages: [
      "/src/assets/dining-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
    ],
    tag: "Dining Table",
    title: "Dining Table Set",
    description: "Table with 4 matching chairs.",
    salePrice: 650,
    price: 850,
  },
  {
    productImages: [
      "/src/assets/dining-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
    ],
    tag: "Dining Table",
    title: "Compact Dining Table",
    description: "Small table for kitchen or small dining area.",
    salePrice: 320,
    price: 400,
  },
  {
    productImages: [
      "/src/assets/dining-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
    ],
    tag: "Dining Table",
    title: "Glass Dining Table Set",
    description: "Table with 6 chairs with glass top.",
    salePrice: 700,
    price: 900,
  },
  {
    productImages: [
      "/src/assets/dining-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
    ],
    tag: "Dining Table",
    title: "Modern Extendable Table",
    description: "Extendable table with modern design.",
    salePrice: 620,
    price: 820,
  },
  {
    productImages: [
      "/src/assets/dining-table.webp",
      "/src/assets/sofa.webp",
      "/src/assets/plastic-table.webp",
      "/src/assets/steel-almirah.webp",
      "/src/assets/folding-bed.webp",
      "/src/assets/wooden-furniture.webp",
      "/src/assets/office-chair.jpeg",
      "/src/assets/plastic-chair.jpeg",
      "/src/assets/matteress.jpeg",
    ],
    tag: "Dining Table",
    title: "Foldable Dining Table",
    description: "Table that folds flat for easy storage.",
    salePrice: 350,
    price: 450,
  },
];
